### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by manuelbcd**
- Added php example to documentation (connection string)
- Added mysqli driver to php-fpm docker image
- Added mariadb dependency to php-fpm in docker-compose file
- Directive added to nginx config to serve static files

### CODE REVIEW

**Comment by stevenliebregt** [comment]
Thanks for opening a pull request! 
I'm not too sure I want to add the MySQLi though, because I left it out intentionally so users could choose. I've been out of the PHP loop for a while so if MySQLi is definitely the better option these days I'll accept it.

**Comment by manuelbcd** [comment]
Hey @stevenliebregt, thank you for your answer.
I did not know that you were deliberately being agnostic.  What if we add it as a comment? or alternatively as an example in README.md to help junior devs to understand how to customize the container.

On the other hand... what do you think about the nginx directive for static files? it is not my speciality but I have noticed that it was not serving static files out-of-the-box.

**Comment by stevenliebregt** [comment]
I like the idea to add it as an example in the readme, the nginx part is really nice!

**Comment by manuelbcd** [comment]
Great @stevenliebregt. I have commented out the mysqli line and removed the connection example from README doc. Please have a look.

**Pull request merged**
